import type { Metadata } from "next"
import { BBH_Sans_Bogle } from "next/font/google"

const bbh = BBH_Sans_Bogle({
  weight: "400",
  subsets: ["latin"],
})

import "./globals.css"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${bbh.className} antialiased`}>{children}</body>
    </html>
  )
}
